setw -g mode-keys vi

# Settings
set-option -g history-limit 1000000
set-option -g allow-rename off

# Clipboard
bind -T copy-mode-vi y send -X copy-pipe-and-cancel "reattach-to-user-namespace pbcopy"

# Mouse on
set-option -g mouse on

# Bindings
# Ctrl-Space as leader
unbind C-b
set -g prefix C-Space
bind Space send-prefix

# Quick-enter copy mode
bind Space copy-mode
# Quick pane cycling
bind C-Space select-pane -t :.+

# # Setup 'v' to begin selection as in Vim
bind-key -Tcopy-mode-vi 'v' send -X begin-selection
# bind-key -Tcopy-mode-vi 'y' send -X copy-selection

# force a reload of the config file
unbind r
bind r source-file ~/.tmux.conf
