cask_args appdir: '/Applications'

tap 'caskroom/cask'
tap 'caskroom/fonts'
tap 'homebrew/bundle'
tap 'homebrew/core'
tap 'versent/taps'

brew 'docker'
brew 'ctags'
brew 'exiftool'
brew 'gdrive'
brew 'git'
brew 'gnu-sed', args: ['with-default-names']
brew 'github/gh/gh'
brew 'go'
brew 'hugo'
brew 'jq'
brew 'lua'
brew 'n'
brew 'openssl'
brew 'p7zip'
brew 'python'
brew 'reattach-to-user-namespace'
brew 'sqlite'
brew 'stow'
brew 'terminal-notifier'
brew 'the_silver_searcher'
brew 'tmux'
brew 'unrar'
brew 'versent/taps/saml2aws'
brew 'versent/taps/unicreds'
brew 'vim', args: ['with-lua']
brew 'wget'
cask 'dropbox'
cask 'font-anonymice-powerline'
cask 'google-chrome'
cask 'iterm2'
cask 'kindle'
cask 'macdown'
cask 'screenflow'
cask 'slack'
cask 'spectacle'
cask 'spotify'
cask 'viscosity'
cask 'vlc'

# brew 'pandoc'
# cask 'calibre'
# cask 'skitch'
# brew 'exercism'
# cask 'starcraft'

# cask 'box-sync'
# cask 'amazon-chime'
# cask 'microsoft-office'
